In [2]:
import numpy as np
import pandas as pd

In [3]:
test_df = pd.read_csv('/kaggle/input/churn-p/churn_predicted (1).csv')

In [4]:
churned_correctly = test_df[(test_df['y_pred'] == 1) & (test_df['y_actual'] == 1)]


num_churned_correctly = len(churned_correctly)
num_churned_correctly

165

In [5]:
total_actual_churn = len(test_df[test_df['y_actual'] == 1])
total_actual_churn

300

In [6]:
total_predicted_churn = len(test_df[test_df['y_pred'] == 1])
total_predicted_churn

222

In [7]:
num_of_customer= test_df.shape[0]
num_of_customer

1500

### Asumsi average cashback/voucher 50k

In [8]:
avg_cashback = 50000

In [9]:
before = num_of_customer * avg_cashback
after = total_predicted_churn * avg_cashback
before

75000000

In [10]:
after

11100000

In [11]:
cost_saved = before-after
cost_saved

63900000

### Cost Needed = Rp 63.900.000

In [12]:
test_df

,creditscore,geography,gender,age,tenure,balance,numofproducts,hascrcard,isactivemember,estimatedsalary,y_actual,y_pred
0,648,Germany,Male,33,7,135310.41,2,0,1,171668.20,0,0
1,713,France,Male,44,1,63438.91,1,1,0,64375.40,0,0
2,712,Spain,Male,47,1,139887.01,1,1,1,95719.73,0,0
3,687,France,Male,38,9,122570.87,1,1,1,35608.88,0,0
4,620,Spain,Male,31,2,166833.86,2,1,1,135171.60,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1495,511,France,Male,27,8,0.00,2,1,1,49089.36,0,0
1496,644,France,Male,33,8,0.00,2,1,1,155294.17,0,0
1497,608,Germany,Female,30,2,91057.37,2,1,0,132973.17,0,0
1498,734,Germany,Female,30,7,123040.38,1,1,1,76503.06,0,0
1499,571,Germany,Female,66,9,111577.01,1,0,1,189271.90,0,0

In [13]:
average_monthly_purchase = test_df['balance'].mean()
average_monthly_purchase

78464.03676666667

In [15]:
Potential_Loss_Before = average_monthly_purchase * 1000 * total_actual_churn *0.1
Potential_Loss_Before

2353921103.0

##### Asumsi 80% dari predicted churn customer berhasil di retain karena diberikan treatment sesuai dengan clusternya

In [16]:
import math
num_cust_retained = (80/100) * num_churned_correctly
num_cust_retained = math.floor(num_cust_retained)
num_cust_retained

132

In [18]:
Potential_Loss_After = Potential_Loss_Before - (average_monthly_purchase * 1000 * num_cust_retained*0.1)
Potential_Loss_After

1318195817.6799998

In [19]:
Revenue_Potential_Gain = (Potential_Loss_Before - Potential_Loss_After) / Potential_Loss_Before
Revenue_Potential_Gain*100

44.00000000000001

### Revenue Potential Gain 44%